// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70wMXwFp2cOMPdTg2jqz_ozeFURP-wgA',
    appId: '1:24513170045:android:46388f67f624722fd1bf14',
    messagingSenderId: '24513170045',
    projectId: 'fir-con2-d2884',
    storageBucket: 'fir-con2-d2884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DCqxs8BN1ILrCtyYNrBkO6nxqK09qfw',
    appId: '1:24513170045:ios:6e0ad6ffa2933a73d1bf14',
    messagingSenderId: '24513170045',
    projectId: 'fir-con2-d2884',
    storageBucket: 'fir-con2-d2884.appspot.com',
    androidClientId: '24513170045-3pmdssrvg2hiht8tp2bgqtjlk2g7s8le.apps.googleusercontent.com',
    iosClientId: '24513170045-k67n81no93kouv51oalgcv6bo42j5jvh.apps.googleusercontent.com',
    iosBundleId: 'pe.project.store.storeappFlutter',
  );
}
